### ISSUE TITLE
/auth/valid api 에러

### ISSUE THREAD

**Issue by AMATEURTOSS** [AMATEURTOSS/ft_transcendence#39]
# 에러 로그
```sh
backend     | valid check error: error: permission denied for table session
backend     |     at Parser.parseErrorMessage (/backend/node_modules/pg-protocol/dist/parser.js:287:98)
backend     |     at Parser.handlePacket (/backend/node_modules/pg-protocol/dist/parser.js:126:29)
backend     |     at Parser.parse (/backend/node_modules/pg-protocol/dist/parser.js:39:38)
backend     |     at Socket.<anonymous> (/backend/node_modules/pg-protocol/dist/index.js:11:42)
backend     |     at Socket.emit (events.js:375:28)
backend     |     at addChunk (internal/streams/readable.js:290:12)
backend     |     at readableAddChunk (internal/streams/readable.js:265:9)
backend     |     at Socket.Readable.push (internal/streams/readable.js:204:10)
backend     |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
backend     |   length: 95,
backend     |   severity: 'ERROR',
backend     |   code: '42501',
backend     |   detail: undefined,
backend     |   hint: undefined,
backend     |   position: undefined,
backend     |   internalPosition: undefined,
backend     |   internalQuery: undefined,
backend     |   where: undefined,
backend     |   schema: undefined,
backend     |   table: undefined,
backend     |   column: undefined,
backend     |   dataType: undefined,
backend     |   constraint: undefined,
backend     |   file: 'aclchk.c',
backend     |   line: '3464',
backend     |   routine: 'aclcheck_error'
backend     | }
```
# 요약
`'http://127.0.0.1:3001/auth/valid'`에 GET 요청 보내면 위와 같은 에러가 뜹니다.
## Request
<img width="592" alt="스크린샷 2021-07-18 오후 3 01 19" src="https://user-images.githubusercontent.com/50163242/126057370-cbc72f92-4ced-4ef1-b987-802355a1d987.png">

### P.S.
현재 improveLoginProcess 브랜치에 버그 구현되어 있으니 확인 부탁드립니다.

**Comment by AMATEURTOSS** [comment]
DB docker image가 업데이트가 안되서 발생한 이슈였음

**Comment by HanGyeolN** [comment]
docker-compose build 문제 

db도 Dockerfile 사용 안하도록 수정 작업중
